### ISSUE TITLE
Warning: Sentry: Symbol upload script is missing. Skipping post build step.

### ISSUE THREAD

**Issue by KyleB97** [getsentry/sentry-unreal#529]
### Environment
Windows

How do you use Sentry?
Sentry SaaS

Which version of the SDK?
0.16.0

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.3.2

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Editor

### Steps to Reproduce
1. Install Sentry-Unreal Git
2. Install Sentry-CLI via NPM
3. Configure Sentry
4. Enable Automatic Symbols upload
5. Package Game

### Expected Result
Package game & upload symbols to Sentry.

### Actual Result
A warning followed by an error 

### Any logs or screenshots
```
UATHelper: Packaging (Windows): ------ Building 1 action(s) started ------
UATHelper: Packaging (Windows): [1/1] cmd Executing post build script (PostBuild-1.bat)
UATHelper: Packaging (Windows): The system cannot find the path specified.
UATHelper: Packaging (Windows): Warning: Sentry: Symbol upload script is missing. Skipping post build step.
UATHelper: Packaging (Windows): Total time in Parallel executor: 0.06 seconds
UATHelper: Packaging (Windows): Total execution time: 2.22 seconds
UATHelper: Packaging (Windows): Took 2.34s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\user\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-Game-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 4s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Warning: Sentry: Symbol upload script is missing. Skipping post build step.
PackagingResults: Error: Unknown Error
```

```
------ Building 1 action(s) started ------
[1/1] cmd Executing post build script (PostBuild-1.bat)
The system cannot find the path specified.
Warning: Sentry: Symbol upload script is missing. Skipping post build step.
Total time in Parallel executor: 0.07 seconds
Total execution time: 3.76 seconds
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActionsAsync(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger, IActionArtifactCache actionArtifactCache) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 417
   at UnrealBuildTool.BuildMode.BuildAsync(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 801
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 411
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 0 changed files of 149 requested writes.
Timeline:

[ 0.000]
[ 0.000](+3.786) <unknown>
[ 3.786]
```

**Comment by KyleB97** [comment]
> @KyleB97 Can you check whether the `upload-debug-symbols-win.bat` script exists in `<YourProjectRoot>/Plugins/Sentry/Scripts` directory? Also, which type of package did you download from the release page - `github` or `marketplace`? In case with the second one symbol uploading scripts have to be installed separately to avoid such issues

Yeah the `upload-debug-symbols-win.bat` is in `/Plugins/Sentry/Scripts` folder, also it was the github version.

**Comment by KyleB97** [comment]
> @KyleB97 Just a few more things to clarify:
> 
> 1. Do you use a binary distribution of the Unreal Engine or build one from sources?
> 2. Have you placed the Sentry plugin into project's `Plugins` directory or installed it to engine directly (i.e `<UEInstallDir/Engine/Plugins/>`)

1. I'm using the binary release currently, I could try building from source if you'd think that would fix it. 
2. The plugin is installed in the projects plugin directory

**Comment by tustanivsky** [comment]
@KyleB97 Essentially this warning comes from the plugin's post-build actions defined in `Sentry.uplugin` file. Since it explicitly mentions that the symbol uploading script is missing I assume its path can't be determined properly for some reason. If you can add some extra output to the `PostBuildSteps -> Win64` section there (i.e. `"echo \"TEST $(PluginDir)\"",` or similar for `SYM_UPLOAD_SCRIPT` variable) that would be really helpful.

**Comment by KyleB97** [comment]
> @KyleB97 Essentially this warning comes from the plugin's post-build actions defined in `Sentry.uplugin` file. Since it explicitly mentions that the symbol uploading script is missing I assume its path can't be determined properly for some reason. If you can add some extra output to the `PostBuildSteps -> Win64` section there (i.e. `"echo \"TEST $(PluginDir)\"",` or similar for `SYM_UPLOAD_SCRIPT` variable) that would be really helpful.

```UATHelper: Packaging (Windows): "TEST C:\Users\kyleb\OneDrive\Documents\Projects\GolfGambit\Unreal 5.3\GolfGambit\Plugins\sentry-unreal-0.16.0"
UATHelper: Packaging (Windows): The system cannot find the path specified.
UATHelper: Packaging (Windows): Warning: Sentry: Symbol upload script is missing. Skipping post build step.
UATHelper: Packaging (Windows): Total time in Parallel executor: 33.11 seconds
PackagingResults: Warning: Sentry: Symbol upload script is missing. Skipping post build step.
UATHelper: Packaging (Windows): Total execution time: 41.14 seconds
UATHelper: Packaging (Windows): Took 41.29s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\kyleb\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-GolfGambit-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 43s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error```

```[12/12] cmd Executing post build script (PostBuild-1.bat)
"TEST C:\Users\kyleb\OneDrive\Documents\Projects\GolfGambit\Unreal 5.3\GolfGambit\Plugins\sentry-unreal-0.16.0"
The system cannot find the path specified.
Warning: Sentry: Symbol upload script is missing. Skipping post build step.
Total time in Parallel executor: 33.11 seconds
Total execution time: 41.14 seconds
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActionsAsync(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger, IActionArtifactCache actionArtifactCache) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 417
   at UnrealBuildTool.BuildMode.BuildAsync(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 801
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 411
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in C:\Program Files\Epic Games\UE_5.3\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 12 changed files of 149 requested writes.
Timeline:

[ 0.000]
[ 0.000](+41.179) <unknown>
[41.179]
```

Seems to link to the plugin fine

**Comment by KyleB97** [comment]
I have a feeling it might be because the directory was too long, I moved my project to a short directory path and it started working.

**Comment by tustanivsky** [comment]
> I have a feeling it might be because the directory was too long, I moved my project to a short directory path and it started working. I'm going to recompile and see if this is a permanent fix later, but thank you for the help so far! It's greatly appreciated. 

Yeah, that might be the case here. Just one more thing I've noticed about the path string in the above log - it contains space which could be a source of errors as well. Anyway, it's great to hear that you've found a workaround!

**Comment by KyleB97** [comment]
Just to confirm, it was because of the spaces! Thank you very much for the help!

**Comment by bitsandfoxes** [comment]
> Just to confirm, it was because of the spaces! 

@tustanivsky can we escape the path to prevent this in the future?
